// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortnoxNetworkEvents.ConsoleApp.Data;

namespace PortnoxNetworkEvents.ConsoleApp.Migrations
{
    [DbContext(typeof(Data.DbContext))]
    partial class DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("PortnoxNetworkEvents.ConsoleApp.Models.NetworkEvent", b =>
                {
                    b.Property<int>("Event_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Device_Mac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Port_Id")
                        .HasColumnType("int");

                    b.Property<string>("Switch_Ip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Event_Id");

                    b.ToTable("NetworkEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
